// config/settings.js
module.exports = {
    PORT: process.env.PORT || 3000,
    MAX_PLAYERS: 6,
    MIN_PLAYERS: 2,
    
    COUNTDOWN_TIME: 60,
    GAME_TIME: 600,
    
    ANIMATION_SYNC_INTERVAL: 50,
    
    PLAYER_MAX_HP: 100,
    PLAYER_REGEN_DELAY: 3000,
    PLAYER_REGEN_AMOUNT: 5,
    PLAYER_REGEN_INTERVAL: 500,
    
    CREEP_SPAWN_INTERVAL: 5000,
    CREEP_MAX_HP: 80,
    CREEP_SPEED: 80,
    CREEP_DAMAGE: 20,
    CREEP_ATTACK_RANGE: 80,
    CREEP_ATTACK_COOLDOWN: 1000,
    CREEP_BARRACKS_ATTACK_RANGE: 160,
    CREEP_SEARCH_RANGE: 380,
    CREEP_SYNC_INTERVAL: 100,
    
    BOT_MAX_HP: 80,
    BOT_SPEED: 100,
    BOT_DAMAGE: 15,
    BOT_ATTACK_RANGE: 70,
    BOT_ATTACK_COOLDOWN: 1500,
    BOT_LIFETIME: 30000,
    BOT_SYNC_INTERVAL: 100,
    MAX_BOTS_PER_PLAYER: 3,
    BOT_DESTROY_DELAY: 5000,
    
    GROUND_Y: 0
};
